loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi # Объем диска под логи

# Включаем сборщик логов с серверов (нод)
promtail:
  enabled: true
  config:
    # Promtail автоматически поймет, куда слать логи внутри этого чарта

# ВЫКЛЮЧАЕМ дублирующие компоненты
grafana:
  enabled: false # Выключена, так как используем Графану из первого чарта

prometheus:
  enabled: false # Выключен, так как используем Прометей из первого чарта