apiVersion: v1
kind: ServiceAccount
metadata:
  name:  rbac-service-account
  namespace: namespace-test-side-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  rbac-service-account
  namespace: namespace-test-side-b
