replicas: 1

tempo:
  repository: grafana/tempo
  tag: ""
  pullPolicy: IfNotPresent

  multitenancyEnabled: false
  reportingEnabled: false
  retention: 720h

  extraArgs:
    config.expand-env: "true"

  storage:
    trace:
      backend: s3
      s3:
        endpoint: IP_PLACEHOLDER:9000
        bucket: tempo-traces
        access_key: ${ACCESS_KEY}
        secret_key: ${SECRET_KEY}
        insecure: true
      wal:
        path: /var/tempo/wal

  extraEnv:
    - name: ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: tempo-minio
          key: access-key
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: tempo-minio
          key: secret-key

  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: IP_PLACEHOLDER:14250
        thrift_binary:
          endpoint: IP_PLACEHOLDER:6832
        thrift_compact:
          endpoint: IP_PLACEHOLDER:6831
        thrift_http:
          endpoint: IP_PLACEHOLDER:14268
    otlp:
      protocols:
        grpc:
          endpoint: "IP_PLACEHOLDER:4317"
        http:
          endpoint: "IP_PLACEHOLDER:4318"

persistence:
  enabled: false

tempoQuery:
  enabled: true
  service:
    port: 16686

service:
  type: ClusterIP

serviceMonitor:
  enabled: true